INSERT INTO public.foods (id, u_id, foodname, price, foodpic) VALUES (92, 44, 'Sajtos-sonkás croissant', 1590, '44Sajtos-sonkás croissant.jpg');
INSERT INTO public.foods (id, u_id, foodname, price, foodpic) VALUES (93, 20, 'Borrito', 990, '20Borrito.jpg');
INSERT INTO public.foods (id, u_id, foodname, price, foodpic) VALUES (53, 42, 'Coca-Cola', 380, '42Coca-Cola.jpg');
INSERT INTO public.foods (id, u_id, foodname, price, foodpic) VALUES (54, 42, 'Fanta', 390, '42Fanta.jpg');
INSERT INTO public.foods (id, u_id, foodname, price, foodpic) VALUES (55, 42, 'Xixo Ice Tea', 370, '42Xixo Ice Tea.jpg');
INSERT INTO public.foods (id, u_id, foodname, price, foodpic) VALUES (56, 42, 'Rakott tészta', 2100, '42Rakott tészta.jpg');
INSERT INTO public.foods (id, u_id, foodname, price, foodpic) VALUES (57, 42, 'Szegedi-gulyásleves', 1200, '42Szegedi-gulyásleves.jpg');
INSERT INTO public.foods (id, u_id, foodname, price, foodpic) VALUES (58, 42, 'Caesar saláta', 1400, '42Caesar saláta.jpg');
INSERT INTO public.foods (id, u_id, foodname, price, foodpic) VALUES (59, 42, 'Sütőtökös pite', 1800, '42Sütőtökös pite.jpg');
INSERT INTO public.foods (id, u_id, foodname, price, foodpic) VALUES (60, 42, 'Lassan sütött marhapofa', 2800, '42Lassan sütött marhapofa.jpg');
INSERT INTO public.foods (id, u_id, foodname, price, foodpic) VALUES (62, 21, 'Karamellás Sajttorta', 790, '21Karamellás Sajttorta.png');
INSERT INTO public.foods (id, u_id, foodname, price, foodpic) VALUES (64, 21, 'Rákóczi túró tart', 650, '21Rákóczi túró tart.png');
INSERT INTO public.foods (id, u_id, foodname, price, foodpic) VALUES (65, 21, 'Croissant', 590, '21Croissant.jpg');
INSERT INTO public.foods (id, u_id, foodname, price, foodpic) VALUES (68, 42, 'Sült csirkemell caprese', 2700, '42Sült csirkemell caprese.jpg');
INSERT INTO public.foods (id, u_id, foodname, price, foodpic) VALUES (70, 21, 'Csokis-almás mousse', 590, '21Csokis-almás mousse.jpg');
INSERT INTO public.foods (id, u_id, foodname, price, foodpic) VALUES (72, 21, 'Csokis-meggyes sütemény', 810, '21Csokis-meggyes sütemény.jpg');
INSERT INTO public.foods (id, u_id, foodname, price, foodpic) VALUES (73, 21, 'Latte', 390, '21Latte.PNG');
INSERT INTO public.foods (id, u_id, foodname, price, foodpic) VALUES (76, 21, 'Karamell Latte', 450, '21Karamell Latte.PNG');
INSERT INTO public.foods (id, u_id, foodname, price, foodpic) VALUES (79, 44, 'Jeges Caramel Macchiato', 1500, '44Jeges Caramel Macchiato.PNG');
INSERT INTO public.foods (id, u_id, foodname, price, foodpic) VALUES (81, 44, 'White Chocolate Mocha', 1500, '44White Chocolate Mocha.PNG');
INSERT INTO public.foods (id, u_id, foodname, price, foodpic) VALUES (82, 44, 'Jeges Caffé Mocha', 1300, '44Jeges Caffé Mocha.PNG');
INSERT INTO public.foods (id, u_id, foodname, price, foodpic) VALUES (84, 44, 'Iced Hibiscus Tea', 1250, '44Iced Hibiscus Tea.PNG');
INSERT INTO public.foods (id, u_id, foodname, price, foodpic) VALUES (86, 44, 'Csokoládés Muffin', 760, '44Csokoládés Muffin.jpg');
INSERT INTO public.foods (id, u_id, foodname, price, foodpic) VALUES (87, 44, 'New York sajttorta', 1140, '44New York sajttorta.jpg');
INSERT INTO public.foods (id, u_id, foodname, price, foodpic) VALUES (89, 44, 'Epres sajttorta', 1120, '44Epres sajttorta.jpg');
INSERT INTO public.foods (id, u_id, foodname, price, foodpic) VALUES (90, 20, 'Pho Leves', 1290, '20Pho Leves.PNG');
INSERT INTO public.foods (id, u_id, foodname, price, foodpic) VALUES (91, 44, 'Almás pite', 890, '44Almás pite.jpg');
INSERT INTO public.foods (id, u_id, foodname, price, foodpic) VALUES (94, 44, 'Brokkoli krémleves', 1470, '44Brokkoli krémleves.jpg');
INSERT INTO public.foods (id, u_id, foodname, price, foodpic) VALUES (95, 20, 'Dupla sajtos Hamburger', 1890, '20Dupla sajtos Hamburger.jpg');
INSERT INTO public.foods (id, u_id, foodname, price, foodpic) VALUES (96, 44, 'Málnás joghurt', 1160, '44Málnás joghurt.jpg');
INSERT INTO public.foods (id, u_id, foodname, price, foodpic) VALUES (97, 44, 'Caffè Misto', 990, '44Caffè Misto.jpg');
INSERT INTO public.foods (id, u_id, foodname, price, foodpic) VALUES (98, 40, 'Saláta tál', 1120, '40Saláta tál.jpg');
INSERT INTO public.foods (id, u_id, foodname, price, foodpic) VALUES (99, 44, 'Klasszikus forró csokoládé', 1240, '44Klasszikus forró csokoládé.jpg');
INSERT INTO public.foods (id, u_id, foodname, price, foodpic) VALUES (100, 20, 'Házi Limonádé', 590, '20Házi Limonádé.PNG');
INSERT INTO public.foods (id, u_id, foodname, price, foodpic) VALUES (101, 44, 'Caramel Frappuccino', 1560, '44Caramel Frappuccino.jpg');
INSERT INTO public.foods (id, u_id, foodname, price, foodpic) VALUES (102, 44, 'Java Chip Frappuccino', 1520, '44Java Chip Frappuccino.jpg');
INSERT INTO public.foods (id, u_id, foodname, price, foodpic) VALUES (104, 44, 'Vanilla Cream Frappuccino', 1520, '44Vanilla Cream Frappuccino.jpg');
INSERT INTO public.foods (id, u_id, foodname, price, foodpic) VALUES (105, 44, 'Strawberries-Cream Frappuccino', 1520, '44Strawberries-Cream Frappuccino.jpg');
INSERT INTO public.foods (id, u_id, foodname, price, foodpic) VALUES (108, 38, 'Creme brulée', 890, '38Creme brulée.avif');
INSERT INTO public.foods (id, u_id, foodname, price, foodpic) VALUES (109, 38, 'Oreo white', 790, '38Oreo white.avif');
INSERT INTO public.foods (id, u_id, foodname, price, foodpic) VALUES (110, 38, 'Cinny apple', 790, '38Cinny apple.avif');
INSERT INTO public.foods (id, u_id, foodname, price, foodpic) VALUES (111, 38, 'Lotus', 1090, '38Lotus.avif');
INSERT INTO public.foods (id, u_id, foodname, price, foodpic) VALUES (113, 38, 'Salted caramel', 890, '38Salted caramel.avif');
INSERT INTO public.foods (id, u_id, foodname, price, foodpic) VALUES (114, 38, 'Everything', 1090, '38Everything.avif');
INSERT INTO public.foods (id, u_id, foodname, price, foodpic) VALUES (115, 38, 'Everything Pink', 1090, '38Everything Pink.avif');
INSERT INTO public.foods (id, u_id, foodname, price, foodpic) VALUES (117, 38, 'Brownie boom', 890, '38Brownie boom.avif');
INSERT INTO public.foods (id, u_id, foodname, price, foodpic) VALUES (118, 38, 'Pistachio & Choco', 1090, '38Pistachio & Choco.avif');
INSERT INTO public.foods (id, u_id, foodname, price, foodpic) VALUES (120, 38, 'Raspberry', 890, '38Raspberry.avif');
INSERT INTO public.foods (id, u_id, foodname, price, foodpic) VALUES (122, 38, 'Nutty', 690, '38Nutty.avif');
INSERT INTO public.foods (id, u_id, foodname, price, foodpic) VALUES (124, 38, 'Mars', 690, '38Mars.avif');
INSERT INTO public.foods (id, u_id, foodname, price, foodpic) VALUES (125, 38, 'NAS coco', 890, '38NAS coco.avif');
INSERT INTO public.foods (id, u_id, foodname, price, foodpic) VALUES (127, 36, 'Mozzarellás szendvics', 780, '36Mozzarellás szendvics.PNG');
INSERT INTO public.foods (id, u_id, foodname, price, foodpic) VALUES (128, 36, 'Sütőtökös pite', 599, '36Sütőtökös pite.PNG');
INSERT INTO public.foods (id, u_id, foodname, price, foodpic) VALUES (129, 36, 'Limonádé több ízben', 695, '36Limonádé több ízben.PNG');
INSERT INTO public.foods (id, u_id, foodname, price, foodpic) VALUES (130, 36, 'Sajtos omlett', 1290, '36Sajtos omlett.PNG');
INSERT INTO public.foods (id, u_id, foodname, price, foodpic) VALUES (131, 36, 'Juhtúrós Bagel', 990, '36Juhtúrós Bagel.PNG');
INSERT INTO public.foods (id, u_id, foodname, price, foodpic) VALUES (132, 36, 'Oreo torta', 550, '36Oreo torta.PNG');
INSERT INTO public.foods (id, u_id, foodname, price, foodpic) VALUES (133, 43, 'Előétel válogatás', 690, '43Előétel válogatás.PNG');
INSERT INTO public.foods (id, u_id, foodname, price, foodpic) VALUES (134, 43, 'Ünnepi Sushi-válogatás', 1590, '43Ünnepi Sushi-válogatás.PNG');
INSERT INTO public.foods (id, u_id, foodname, price, foodpic) VALUES (135, 43, 'Garnélás Pad Thai', 1890, '43Garnélás Pad Thai.PNG');
INSERT INTO public.foods (id, u_id, foodname, price, foodpic) VALUES (136, 43, 'Sushi Tál', 4390, '43Sushi Tál.PNG');
INSERT INTO public.foods (id, u_id, foodname, price, foodpic) VALUES (137, 43, 'Lazac', 2300, '43Lazac.PNG');
INSERT INTO public.foods (id, u_id, foodname, price, foodpic) VALUES (138, 25, 'Baconos tükörtojásos Sub ', 990, '25Baconos tükörtojásos Sub .avif');
INSERT INTO public.foods (id, u_id, foodname, price, foodpic) VALUES (139, 25, 'Sajtos tükörtojásos Sub', 790, '25Sajtos tükörtojásos Sub.avif');
INSERT INTO public.foods (id, u_id, foodname, price, foodpic) VALUES (140, 25, 'Csirke Teriyaki Sub', 1490, '25Csirke Teriyaki Sub.avif');
INSERT INTO public.foods (id, u_id, foodname, price, foodpic) VALUES (141, 25, 'Steak és Sajt Sub', 1490, '25Steak és Sajt Sub.avif');
INSERT INTO public.foods (id, u_id, foodname, price, foodpic) VALUES (142, 25, 'Majonézes Tonhal Sub', 1370, '25Majonézes Tonhal Sub.avif');
INSERT INTO public.foods (id, u_id, foodname, price, foodpic) VALUES (143, 25, 'Italian B.M.T. Sub', 1210, '25Italian B.M.T. Sub.avif');
INSERT INTO public.foods (id, u_id, foodname, price, foodpic) VALUES (144, 25, 'Olasz fűszeres Sub', 1090, '25Olasz fűszeres Sub.avif');
INSERT INTO public.foods (id, u_id, foodname, price, foodpic) VALUES (145, 25, 'BBQ Csirkés Sub', 1490, '25BBQ Csirkés Sub.avif');
INSERT INTO public.foods (id, u_id, foodname, price, foodpic) VALUES (146, 25, 'B.L.T. Sub', 1050, '25B.L.T. Sub.avif');
INSERT INTO public.foods (id, u_id, foodname, price, foodpic) VALUES (147, 25, 'Fűszeres vegán Sub', 1260, '25Fűszeres vegán Sub.avif');
INSERT INTO public.foods (id, u_id, foodname, price, foodpic) VALUES (148, 25, 'BBQ Ribs Sub', 1290, '25BBQ Ribs Sub.avif');
INSERT INTO public.foods (id, u_id, foodname, price, foodpic) VALUES (149, 25, 'Sonkás Sub', 1920, '25Sonkás Sub.avif');
INSERT INTO public.foods (id, u_id, foodname, price, foodpic) VALUES (150, 25, 'BLT Sub', 2100, '25BLT Sub.avif');
INSERT INTO public.foods (id, u_id, foodname, price, foodpic) VALUES (151, 25, 'Roston Csirke Sub', 2280, '25Roston Csirke Sub.avif');
INSERT INTO public.foods (id, u_id, foodname, price, foodpic) VALUES (152, 25, 'Csirke Teriyaki saláta', 1820, '25Csirke Teriyaki saláta.avif');
INSERT INTO public.foods (id, u_id, foodname, price, foodpic) VALUES (153, 39, 'Húsimádó', 1190, '39Húsimádó.jpg');
INSERT INTO public.foods (id, u_id, foodname, price, foodpic) VALUES (154, 25, 'Tonhal saláta', 1710, '25Tonhal saláta.avif');
INSERT INTO public.foods (id, u_id, foodname, price, foodpic) VALUES (155, 39, 'Rukkolás pizza', 1220, '39Rukkolás pizza.jpg');
INSERT INTO public.foods (id, u_id, foodname, price, foodpic) VALUES (156, 25, 'Roston csirkés saláta', 1480, '25Roston csirkés saláta.avif');
INSERT INTO public.foods (id, u_id, foodname, price, foodpic) VALUES (157, 39, 'Olaszos pizza', 1590, '39Olaszos pizza.jpg');
INSERT INTO public.foods (id, u_id, foodname, price, foodpic) VALUES (158, 25, 'Sült Krumpli', 570, '25Sült Krumpli.avif');
INSERT INTO public.foods (id, u_id, foodname, price, foodpic) VALUES (159, 25, 'Naturaqua ásványvíz 0,5l', 450, '25Naturaqua ásványvíz 0,5l.avif');
INSERT INTO public.foods (id, u_id, foodname, price, foodpic) VALUES (160, 25, 'Coca-cola', 400, '25Coca-cola.jpg');
INSERT INTO public.foods (id, u_id, foodname, price, foodpic) VALUES (161, 39, 'Brokkis pizza', 1600, '39Brokkis pizza.jpg');
INSERT INTO public.foods (id, u_id, foodname, price, foodpic) VALUES (162, 40, 'Szalámis pizza', 700, '40Szalámis pizza.jpg');
INSERT INTO public.foods (id, u_id, foodname, price, foodpic) VALUES (164, 40, 'Topjoy kaktusz', 150, '40Topjoy kaktusz.jpg');
INSERT INTO public.foods (id, u_id, foodname, price, foodpic) VALUES (165, 40, 'Nestea barack', 360, '40Nestea barack.jpg');
INSERT INTO public.foods (id, u_id, foodname, price, foodpic) VALUES (166, 40, 'Sültburgonya', 230, '40Sültburgonya.jpg');
INSERT INTO public.foods (id, u_id, foodname, price, foodpic) VALUES (167, 40, 'Saláta tál', 1120, '40Saláta tál.jpg');
INSERT INTO public.foods (id, u_id, foodname, price, foodpic) VALUES (168, 40, 'Nestea citrom', 360, '40Nestea citrom.jpg');
INSERT INTO public.foods (id, u_id, foodname, price, foodpic) VALUES (169, 40, 'Görög Saláta', 1200, '40Görög Saláta.png');
INSERT INTO public.foods (id, u_id, foodname, price, foodpic) VALUES (171, 40, 'Narancslé', 290, '40Narancslé.png');
INSERT INTO public.foods (id, u_id, foodname, price, foodpic) VALUES (173, 40, 'Almalé', 270, '40Almalé.png');
INSERT INTO public.foods (id, u_id, foodname, price, foodpic) VALUES (175, 40, 'Túrógombóc', 890, '40Túrógombóc.jpg');
INSERT INTO public.foods (id, u_id, foodname, price, foodpic) VALUES (177, 40, 'Vaníliás kávé', 360, '40Vaníliás kávé.jpg');
INSERT INTO public.foods (id, u_id, foodname, price, foodpic) VALUES (178, 40, 'Barack üdítő', 290, '40Barack üdítő.png');
INSERT INTO public.foods (id, u_id, foodname, price, foodpic) VALUES (179, 40, 'Hosszú kávé', 350, '40Hosszú kávé.png');
INSERT INTO public.foods (id, u_id, foodname, price, foodpic) VALUES (180, 41, 'Bacon King', 2090, '41Bacon King.png');
INSERT INTO public.foods (id, u_id, foodname, price, foodpic) VALUES (181, 40, 'Extra Sajtos Pizza', 670, '40Extra Sajtos Pizza.jpg');
INSERT INTO public.foods (id, u_id, foodname, price, foodpic) VALUES (182, 40, 'Expresso kávé', 300, '40Expresso kávé.jpg');
INSERT INTO public.foods (id, u_id, foodname, price, foodpic) VALUES (183, 41, 'Lord Mustard', 2590, '41Lord Mustard.png');
INSERT INTO public.foods (id, u_id, foodname, price, foodpic) VALUES (184, 40, 'Sajtburger', 410, '40Sajtburger.png');
INSERT INTO public.foods (id, u_id, foodname, price, foodpic) VALUES (185, 41, 'Sir Chimichurri', 2590, '41Sir Chimichurri.png');
INSERT INTO public.foods (id, u_id, foodname, price, foodpic) VALUES (186, 41, 'Gluténmentes WHOPPER', 2100, '41Gluténmentes WHOPPER.png');
INSERT INTO public.foods (id, u_id, foodname, price, foodpic) VALUES (187, 41, 'WHOPPER', 1490, '41WHOPPER.jpg');
INSERT INTO public.foods (id, u_id, foodname, price, foodpic) VALUES (188, 41, 'Dupla Chili Cheese burger', 690, '41Dupla Chili Cheese burger.png');
INSERT INTO public.foods (id, u_id, foodname, price, foodpic) VALUES (189, 41, 'Dupla sajtburger', 790, '41Dupla sajtburger.png');
INSERT INTO public.foods (id, u_id, foodname, price, foodpic) VALUES (190, 41, 'Sajtburger', 390, '41Sajtburger.png');
INSERT INTO public.foods (id, u_id, foodname, price, foodpic) VALUES (191, 41, 'Texas szendvics', 1100, '41Texas szendvics.png');
INSERT INTO public.foods (id, u_id, foodname, price, foodpic) VALUES (192, 41, 'Xtra Long Big King', 1290, '41Xtra Long Big King.png');
INSERT INTO public.foods (id, u_id, foodname, price, foodpic) VALUES (193, 41, 'King nuggets', 800, '41King nuggets.png');
INSERT INTO public.foods (id, u_id, foodname, price, foodpic) VALUES (194, 41, 'Nuggets Burger', 490, '41Nuggets Burger.png');
INSERT INTO public.foods (id, u_id, foodname, price, foodpic) VALUES (195, 41, 'Crispy Chicken', 490, '41Crispy Chicken.png');
INSERT INTO public.foods (id, u_id, foodname, price, foodpic) VALUES (196, 41, 'Egyszemélyes kosár', 1590, '41Egyszemélyes kosár.png');
INSERT INTO public.foods (id, u_id, foodname, price, foodpic) VALUES (197, 41, 'Spicy kosár', 1590, '41Spicy kosár.png');
INSERT INTO public.foods (id, u_id, foodname, price, foodpic) VALUES (198, 41, 'Páros kosár', 2190, '41Páros kosár.png');
INSERT INTO public.foods (id, u_id, foodname, price, foodpic) VALUES (199, 41, 'King Saláta', 1090, '41King Saláta.png');
INSERT INTO public.foods (id, u_id, foodname, price, foodpic) VALUES (200, 41, 'Joghurtos öntet', 290, '41Joghurtos öntet.png');
INSERT INTO public.foods (id, u_id, foodname, price, foodpic) VALUES (201, 41, 'Coca-Cola', 390, '41Coca-Cola.jpg');
INSERT INTO public.foods (id, u_id, foodname, price, foodpic) VALUES (202, 41, 'Fanta', 390, '41Fanta.jpg');
INSERT INTO public.foods (id, u_id, foodname, price, foodpic) VALUES (203, 41, 'Latte macchiato', 390, '41Latte macchiato.png');
INSERT INTO public.foods (id, u_id, foodname, price, foodpic) VALUES (204, 41, 'Gouda Sajtfalatok', 590, '41Gouda Sajtfalatok.png');
INSERT INTO public.foods (id, u_id, foodname, price, foodpic) VALUES (205, 41, 'Sült krumpli', 390, '41Sült krumpli.png');
INSERT INTO public.foods (id, u_id, foodname, price, foodpic) VALUES (206, 41, 'Édesburgonya', 420, '41Édesburgonya.png');
INSERT INTO public.foods (id, u_id, foodname, price, foodpic) VALUES (207, 41, 'Spicy King Nuggets', 690, '41Spicy King Nuggets.png');
INSERT INTO public.foods (id, u_id, foodname, price, foodpic) VALUES (208, 41, 'Hagymakarika', 590, '41Hagymakarika.png');
INSERT INTO public.foods (id, u_id, foodname, price, foodpic) VALUES (209, 41, 'Chili Cheese Nuggets', 590, '41Chili Cheese Nuggets.png');
INSERT INTO public.foods (id, u_id, foodname, price, foodpic) VALUES (210, 41, 'Ketchup', 190, '41Ketchup.png');
INSERT INTO public.foods (id, u_id, foodname, price, foodpic) VALUES (211, 41, 'Majonéz', 190, '41Majonéz.png');
INSERT INTO public.foods (id, u_id, foodname, price, foodpic) VALUES (212, 41, 'BBQ szósz', 190, '41BBQ szósz.png');
INSERT INTO public.foods (id, u_id, foodname, price, foodpic) VALUES (213, 41, 'Curry-mangó szósz', 190, '41Curry-mangó szósz.png');
INSERT INTO public.foods (id, u_id, foodname, price, foodpic) VALUES (214, 41, 'Édes-savanyú szósz', 190, '41Édes-savanyú szósz.png');
INSERT INTO public.foods (id, u_id, foodname, price, foodpic) VALUES (215, 41, 'Oreo KING FUSION', 690, '41Oreo KING FUSION.png');
INSERT INTO public.foods (id, u_id, foodname, price, foodpic) VALUES (216, 41, 'Fagylalt csokoládé ízű ', 690, '41Fagylalt csokoládé ízű .png');
INSERT INTO public.foods (id, u_id, foodname, price, foodpic) VALUES (217, 41, 'Brownie Cheesecake', 540, '41Brownie Cheesecake.png');
INSERT INTO public.foods (id, u_id, foodname, price, foodpic) VALUES (218, 41, 'Brownie fagyival', 410, '41Brownie fagyival.png');
INSERT INTO public.foods (id, u_id, foodname, price, foodpic) VALUES (219, 41, 'Belga gofri', 570, '41Belga gofri.png');
INSERT INTO public.foods (id, u_id, foodname, price, foodpic) VALUES (221, 37, 'Sajtos McRoyal', 950, '37Sajtos McRoyal.png');
INSERT INTO public.foods (id, u_id, foodname, price, foodpic) VALUES (222, 37, 'Big Mac', 960, '37Big Mac.png');
INSERT INTO public.foods (id, u_id, foodname, price, foodpic) VALUES (223, 37, 'Sajtburger', 490, '37Sajtburger.png');
INSERT INTO public.foods (id, u_id, foodname, price, foodpic) VALUES (224, 37, 'Dupla Sajtburger', 590, '37Dupla Sajtburger.png');
INSERT INTO public.foods (id, u_id, foodname, price, foodpic) VALUES (225, 37, 'Gluténmentes Sajtos McRoyal', 890, '37Gluténmentes Sajtos McRoyal.png');
INSERT INTO public.foods (id, u_id, foodname, price, foodpic) VALUES (226, 37, 'Country burger', 990, '37Country burger.png');
INSERT INTO public.foods (id, u_id, foodname, price, foodpic) VALUES (227, 37, 'McChicken®', 1090, '37McChicken®.png');
INSERT INTO public.foods (id, u_id, foodname, price, foodpic) VALUES (228, 37, 'Maestro Wrap Wanda', 1290, '37Maestro Wrap Wanda.png');
INSERT INTO public.foods (id, u_id, foodname, price, foodpic) VALUES (229, 37, 'Sertés McFarm', 1290, '37Sertés McFarm.png');
INSERT INTO public.foods (id, u_id, foodname, price, foodpic) VALUES (230, 37, 'Dupla Filet-O-Fish', 1290, '37Dupla Filet-O-Fish.png');
INSERT INTO public.foods (id, u_id, foodname, price, foodpic) VALUES (231, 37, 'Filet-O-Fish', 990, '37Filet-O-Fish.png');
INSERT INTO public.foods (id, u_id, foodname, price, foodpic) VALUES (232, 37, 'Chicken McNuggets', 890, '37Chicken McNuggets.png');
INSERT INTO public.foods (id, u_id, foodname, price, foodpic) VALUES (233, 37, 'Halrudak', 890, '37Halrudak.png');
INSERT INTO public.foods (id, u_id, foodname, price, foodpic) VALUES (234, 37, 'Édesburgonya', 560, '37Édesburgonya.png');
INSERT INTO public.foods (id, u_id, foodname, price, foodpic) VALUES (235, 37, 'Cézár saláta', 1090, '37Cézár saláta.png');
INSERT INTO public.foods (id, u_id, foodname, price, foodpic) VALUES (236, 37, 'Sárgarépakorongok', 360, '37Sárgarépakorongok.png');
INSERT INTO public.foods (id, u_id, foodname, price, foodpic) VALUES (237, 37, 'Burgonya', 410, '37Burgonya.png');
INSERT INTO public.foods (id, u_id, foodname, price, foodpic) VALUES (238, 37, 'Curry szósz', 190, '37Curry szósz.png');
INSERT INTO public.foods (id, u_id, foodname, price, foodpic) VALUES (239, 37, 'Chili-paprikás szósz', 190, '37Chili-paprikás szósz.png');
INSERT INTO public.foods (id, u_id, foodname, price, foodpic) VALUES (240, 37, 'Mézes-mustáros szósz', 190, '37Mézes-mustáros szósz.png');
INSERT INTO public.foods (id, u_id, foodname, price, foodpic) VALUES (241, 37, 'Barbecue szósz', 190, '37Barbecue szósz.png');
INSERT INTO public.foods (id, u_id, foodname, price, foodpic) VALUES (242, 37, 'Majonéz', 190, '37Majonéz.png');
INSERT INTO public.foods (id, u_id, foodname, price, foodpic) VALUES (243, 37, 'Ketchup', 190, '37Ketchup.png');
INSERT INTO public.foods (id, u_id, foodname, price, foodpic) VALUES (244, 37, 'Fokhagymás mártogató szósz', 190, '37Fokhagymás mártogató szósz.png');
INSERT INTO public.foods (id, u_id, foodname, price, foodpic) VALUES (245, 37, 'McFlurry Pöttyös Natúr', 790, '37McFlurry Pöttyös Natúr.png');
INSERT INTO public.foods (id, u_id, foodname, price, foodpic) VALUES (246, 37, 'McFlurry M&M''s', 890, '37McFlurry M&M''s.png');
INSERT INTO public.foods (id, u_id, foodname, price, foodpic) VALUES (247, 37, 'Forró almás pite', 1020, '37Forró almás pite.png');
INSERT INTO public.foods (id, u_id, foodname, price, foodpic) VALUES (248, 37, 'Vaníliás töltött fánk', 490, '37Vaníliás töltött fánk.png');
INSERT INTO public.foods (id, u_id, foodname, price, foodpic) VALUES (249, 37, 'Coca-Cola', 390, '37Coca-Cola.jpg');
INSERT INTO public.foods (id, u_id, foodname, price, foodpic) VALUES (250, 37, 'Fanta', 400, '37Fanta.jpg');
INSERT INTO public.foods (id, u_id, foodname, price, foodpic) VALUES (252, 39, 'Kolbászos pizza', 1090, '39Kolbászos pizza.jpg');
INSERT INTO public.foods (id, u_id, foodname, price, foodpic) VALUES (253, 39, 'Honeymoon pizza', 1490, '39Honeymoon pizza.jpg');
INSERT INTO public.foods (id, u_id, foodname, price, foodpic) VALUES (254, 39, 'Hawaii pizza', 1290, '39Hawaii pizza.jpg');
INSERT INTO public.foods (id, u_id, foodname, price, foodpic) VALUES (255, 39, 'Ízbomba pizza', 1590, '39Ízbomba pizza.jpg');
INSERT INTO public.foods (id, u_id, foodname, price, foodpic) VALUES (256, 39, 'Kakukktojás pizza', 1490, '39Kakukktojás pizza.jpg');
INSERT INTO public.foods (id, u_id, foodname, price, foodpic) VALUES (257, 39, 'Karcsi kedvence pizza', 1690, '39Karcsi kedvence pizza.jpg');
INSERT INTO public.foods (id, u_id, foodname, price, foodpic) VALUES (258, 39, 'Mexikói pizza', 1590, '39Mexikói pizza.jpg');
INSERT INTO public.foods (id, u_id, foodname, price, foodpic) VALUES (259, 39, 'Olivás-fetás pizza', 1290, '39Olivás-fetás pizza.jpg');
INSERT INTO public.foods (id, u_id, foodname, price, foodpic) VALUES (260, 39, 'Piedone pizza', 1390, '39Piedone pizza.jpg');
INSERT INTO public.foods (id, u_id, foodname, price, foodpic) VALUES (261, 39, 'Son-Go-Ku pizza', 1690, '39Son-Go-Ku pizza.jpg');
INSERT INTO public.foods (id, u_id, foodname, price, foodpic) VALUES (262, 39, 'Tanyasi pizza', 1490, '39Tanyasi pizza.jpg');
INSERT INTO public.foods (id, u_id, foodname, price, foodpic) VALUES (263, 39, 'Tonhal pizza', 1490, '39Tonhal pizza.jpg');
INSERT INTO public.foods (id, u_id, foodname, price, foodpic) VALUES (264, 39, 'Vegetáriánus pizza', 1790, '39Vegetáriánus pizza.jpg');
INSERT INTO public.foods (id, u_id, foodname, price, foodpic) VALUES (265, 46, 'Erdős-tortaszelet', 1190, '46Erdős-tortaszelet.avif');
INSERT INTO public.foods (id, u_id, foodname, price, foodpic) VALUES (266, 46, 'Albrecht-torta szelet', 1100, '46Albrecht-torta szelet.avif');
INSERT INTO public.foods (id, u_id, foodname, price, foodpic) VALUES (267, 46, 'Epres-nutellás tortaszelet', 990, '46Epres-nutellás tortaszelet.avif');
INSERT INTO public.foods (id, u_id, foodname, price, foodpic) VALUES (268, 46, 'Málnás trüffeltorta szelet', 890, '46Málnás trüffeltorta szelet.avif');
INSERT INTO public.foods (id, u_id, foodname, price, foodpic) VALUES (269, 46, 'Mandorla', 590, '46Mandorla.avif');
INSERT INTO public.foods (id, u_id, foodname, price, foodpic) VALUES (270, 46, 'Eszterházy-torta', 990, '46Eszterházy-torta.avif');
INSERT INTO public.foods (id, u_id, foodname, price, foodpic) VALUES (271, 46, 'Sajtos rudacskák', 1220, '46Sajtos rudacskák.avif');
INSERT INTO public.foods (id, u_id, foodname, price, foodpic) VALUES (272, 46, 'Somlói Galuska', 990, '46Somlói Galuska.avif');
INSERT INTO public.foods (id, u_id, foodname, price, foodpic) VALUES (273, 46, 'Kávés mignon', 550, '46Kávés mignon.avif');
INSERT INTO public.foods (id, u_id, foodname, price, foodpic) VALUES (278, 46, 'Linzer', 650, '46Linzer.avif');
INSERT INTO public.foods (id, u_id, foodname, price, foodpic) VALUES (279, 46, 'Isler', 550, '46Isler.avif');
INSERT INTO public.foods (id, u_id, foodname, price, foodpic) VALUES (280, 46, 'Túró Rudi gofri', 1550, '46Túró Rudi gofri.avif');
INSERT INTO public.foods (id, u_id, foodname, price, foodpic) VALUES (281, 46, 'Coca-Cola', 350, '46Coca-Cola.jpg');
INSERT INTO public.foods (id, u_id, foodname, price, foodpic) VALUES (282, 46, 'Fanta', 370, '46Fanta.jpg');
INSERT INTO public.foods (id, u_id, foodname, price, foodpic) VALUES (284, 35, 'Pad kee mao', 2690, '35Pad kee mao.avif');
INSERT INTO public.foods (id, u_id, foodname, price, foodpic) VALUES (285, 35, 'Kao pad', 2590, '35Kao pad.avif');
INSERT INTO public.foods (id, u_id, foodname, price, foodpic) VALUES (286, 35, 'Teriyaki csirke', 2790, '35Teriyaki csirke.avif');
INSERT INTO public.foods (id, u_id, foodname, price, foodpic) VALUES (287, 35, 'Rostonsült fokhagymás lazac', 3990, '35Rostonsült fokhagymás lazac.avif');
INSERT INTO public.foods (id, u_id, foodname, price, foodpic) VALUES (288, 35, 'Teriyaki lazac steak', 3990, '35Teriyaki lazac steak.avif');
INSERT INTO public.foods (id, u_id, foodname, price, foodpic) VALUES (289, 35, 'Mogyorós csirke', 2990, '35Mogyorós csirke.avif');
INSERT INTO public.foods (id, u_id, foodname, price, foodpic) VALUES (290, 35, 'Mézes csirke tojással', 2490, '35Mézes csirke tojással.avif');
INSERT INTO public.foods (id, u_id, foodname, price, foodpic) VALUES (291, 35, 'Lazac sashimi', 2290, '35Lazac sashimi.avif');
INSERT INTO public.foods (id, u_id, foodname, price, foodpic) VALUES (292, 35, 'Vörös tonhal sashimi', 2390, '35Vörös tonhal sashimi.avif');
INSERT INTO public.foods (id, u_id, foodname, price, foodpic) VALUES (293, 35, 'Surimi sashimi', 1990, '35Surimi sashimi.avif');
INSERT INTO public.foods (id, u_id, foodname, price, foodpic) VALUES (294, 35, 'Amago nigiri', 390, '35Amago nigiri.avif');
INSERT INTO public.foods (id, u_id, foodname, price, foodpic) VALUES (295, 35, 'Teriyaki lazac nigiri', 590, '35Teriyaki lazac nigiri.avif');
INSERT INTO public.foods (id, u_id, foodname, price, foodpic) VALUES (296, 35, 'Lazac nigiri', 590, '35Lazac nigiri.avif');
INSERT INTO public.foods (id, u_id, foodname, price, foodpic) VALUES (297, 35, 'Garnéla nigiri', 690, '35Garnéla nigiri.avif');
INSERT INTO public.foods (id, u_id, foodname, price, foodpic) VALUES (298, 35, 'Surimi nigiri', 490, '35Surimi nigiri.avif');
INSERT INTO public.foods (id, u_id, foodname, price, foodpic) VALUES (299, 35, 'Spárga maki', 890, '35Spárga maki.avif');
INSERT INTO public.foods (id, u_id, foodname, price, foodpic) VALUES (300, 35, 'Édesburgonya maki', 790, '35Édesburgonya maki.avif');
INSERT INTO public.foods (id, u_id, foodname, price, foodpic) VALUES (301, 35, 'Uborka maki', 710, '35Uborka maki.avif');
INSERT INTO public.foods (id, u_id, foodname, price, foodpic) VALUES (302, 35, 'Lazac maki', 1090, '35Lazac maki.avif');
INSERT INTO public.foods (id, u_id, foodname, price, foodpic) VALUES (303, 35, 'Vörös tonhal maki', 1290, '35Vörös tonhal maki.avif');
INSERT INTO public.foods (id, u_id, foodname, price, foodpic) VALUES (304, 35, 'Teriyaki lazac maki', 1390, '35Teriyaki lazac maki.avif');
INSERT INTO public.foods (id, u_id, foodname, price, foodpic) VALUES (305, 35, 'Kombináció A (12db)', 3090, '35Kombináció A (12db).avif');
INSERT INTO public.foods (id, u_id, foodname, price, foodpic) VALUES (306, 35, 'Kombináció B (20db)', 3390, '35Kombináció B (20db).avif');
INSERT INTO public.foods (id, u_id, foodname, price, foodpic) VALUES (307, 35, 'Kombináció C (15db)', 3990, '35Kombináció C (15db).avif');
INSERT INTO public.foods (id, u_id, foodname, price, foodpic) VALUES (308, 35, 'Kombináció D (15db)', 3390, '35Kombináció D (15db).avif');
INSERT INTO public.foods (id, u_id, foodname, price, foodpic) VALUES (309, 35, 'Kombináció E (20db)', 3990, '35Kombináció E (20db).avif');
INSERT INTO public.foods (id, u_id, foodname, price, foodpic) VALUES (310, 35, 'Kombináció Jack A (30db)', 6590, '35Kombináció Jack A (30db).avif');
INSERT INTO public.foods (id, u_id, foodname, price, foodpic) VALUES (311, 35, 'Kombináció Jack B (21db)', 5990, '35Kombináció Jack B (21db).avif');
INSERT INTO public.foods (id, u_id, foodname, price, foodpic) VALUES (312, 35, 'Kombináció Jack C (38db)', 9790, '35Kombináció Jack C (38db).avif');
INSERT INTO public.foods (id, u_id, foodname, price, foodpic) VALUES (313, 35, 'Kombináció Jack D (49db)', 12900, '35Kombináció Jack D (49db).avif');
INSERT INTO public.foods (id, u_id, foodname, price, foodpic) VALUES (314, 35, 'Fűszeres csirke roll', 2900, '35Fűszeres csirke roll.avif');
INSERT INTO public.foods (id, u_id, foodname, price, foodpic) VALUES (315, 35, 'Banán lotti', 990, '35Banán lotti.avif');
INSERT INTO public.foods (id, u_id, foodname, price, foodpic) VALUES (316, 10, 'Grander Box', 2490, '10Grander Box.png');
INSERT INTO public.foods (id, u_id, foodname, price, foodpic) VALUES (317, 10, 'Kentucky Gold Wrapper Box', 2690, '10Kentucky Gold Wrapper Box.png');
INSERT INTO public.foods (id, u_id, foodname, price, foodpic) VALUES (318, 10, '15 Strips Kosár', 3590, '1015 Strips Kosár.png');
INSERT INTO public.foods (id, u_id, foodname, price, foodpic) VALUES (319, 10, '30 Strips Kosár', 5990, '1030 Strips Kosár.png');
INSERT INTO public.foods (id, u_id, foodname, price, foodpic) VALUES (320, 10, 'Poké Bowl California Sun', 1790, '10Poké Bowl California Sun.png');
INSERT INTO public.foods (id, u_id, foodname, price, foodpic) VALUES (322, 10, 'Kentucky Gold Wrapper', 1590, '10Kentucky Gold Wrapper.png');
INSERT INTO public.foods (id, u_id, foodname, price, foodpic) VALUES (323, 10, 'Smoky BBQ Wrapper Box', 2690, '10Smoky BBQ Wrapper Box.png');
INSERT INTO public.foods (id, u_id, foodname, price, foodpic) VALUES (324, 10, 'Smoky BBQ Wrapper', 1590, '10Smoky BBQ Wrapper.png');
INSERT INTO public.foods (id, u_id, foodname, price, foodpic) VALUES (325, 10, 'Spicy Harissa Wrapper Menü', 2190, '10Spicy Harissa Wrapper Menü.png');
INSERT INTO public.foods (id, u_id, foodname, price, foodpic) VALUES (326, 10, 'Spicy Harissa Wrapper', 1590, '10Spicy Harissa Wrapper.png');
INSERT INTO public.foods (id, u_id, foodname, price, foodpic) VALUES (327, 10, 'Collect iTwist Menü', 790, '10Collect iTwist Menü.png');
INSERT INTO public.foods (id, u_id, foodname, price, foodpic) VALUES (328, 10, '2 Egyszemélyes Kosár', 1790, '102 Egyszemélyes Kosár.png');
INSERT INTO public.foods (id, u_id, foodname, price, foodpic) VALUES (329, 10, 'Mega Kosár', 6990, '10Mega Kosár.png');
INSERT INTO public.foods (id, u_id, foodname, price, foodpic) VALUES (330, 10, 'Édes Csili Rizs Box Menü', 1590, '10Édes Csili Rizs Box Menü.png');
INSERT INTO public.foods (id, u_id, foodname, price, foodpic) VALUES (331, 10, 'Classic XL Kosár', 4990, '10Classic XL Kosár.png');
INSERT INTO public.foods (id, u_id, foodname, price, foodpic) VALUES (332, 10, 'Kentucky Gold Grander Menü', 2190, '10Kentucky Gold Grander Menü.png');
INSERT INTO public.foods (id, u_id, foodname, price, foodpic) VALUES (333, 10, 'Dupla Zinger Menü', 2290, '10Dupla Zinger Menü.png');
INSERT INTO public.foods (id, u_id, foodname, price, foodpic) VALUES (334, 10, 'Grander', 1490, '10Grander.png');
INSERT INTO public.foods (id, u_id, foodname, price, foodpic) VALUES (335, 10, 'Kentucky Gold Grander', 1590, '10Kentucky Gold Grander.png');
INSERT INTO public.foods (id, u_id, foodname, price, foodpic) VALUES (336, 10, 'Shake Deluxe: Mango Nagy', 590, '10Shake Deluxe: Mango Nagy.png');
INSERT INTO public.foods (id, u_id, foodname, price, foodpic) VALUES (337, 10, 'Shake Deluxe: Mogyoróvajas', 550, '10Shake Deluxe: Mogyoróvajas.png');
INSERT INTO public.foods (id, u_id, foodname, price, foodpic) VALUES (338, 10, 'Shake Deluxe Csokis', 550, '10Shake Deluxe Csokis.png');
INSERT INTO public.foods (id, u_id, foodname, price, foodpic) VALUES (339, 10, 'Hagymakarika Kosár', 890, '10Hagymakarika Kosár.png');
INSERT INTO public.foods (id, u_id, foodname, price, foodpic) VALUES (340, 10, 'Normál sült burgonya', 590, '10Normál sült burgonya.png');
INSERT INTO public.foods (id, u_id, foodname, price, foodpic) VALUES (341, 10, '3 választható szósz', 290, '103 választható szósz.png');
INSERT INTO public.foods (id, u_id, foodname, price, foodpic) VALUES (342, 10, 'Kis kukorica', 290, '10Kis kukorica.png');
INSERT INTO public.foods (id, u_id, foodname, price, foodpic) VALUES (343, 10, 'Coca-Cola', 380, '10Coca-Cola.jpg');
INSERT INTO public.foods (id, u_id, foodname, price, foodpic) VALUES (344, 10, 'Fanta', 390, '10Fanta.jpg');