INSERT INTO public.locations (id, u_id, postcode, city, street, streetnumber, other) VALUES (14, 17, 6000, 'Szeged', 'Csanádi', 17, '9/52');
INSERT INTO public.locations (id, u_id, postcode, city, street, streetnumber, other) VALUES (16, 20, 6720, 'Szeged', 'Tisza Lajos krt.', 76, '');
INSERT INTO public.locations (id, u_id, postcode, city, street, streetnumber, other) VALUES (17, 21, 6720, 'Szeged', 'Tisza Lajos krt.', 40, '');
INSERT INTO public.locations (id, u_id, postcode, city, street, streetnumber, other) VALUES (22, 25, 6726, 'Szeged', 'Tisza Lajos krt.', 1, '');
INSERT INTO public.locations (id, u_id, postcode, city, street, streetnumber, other) VALUES (25, 28, 6000, 'Szeged', 'Rigó', 10, '');
INSERT INTO public.locations (id, u_id, postcode, city, street, streetnumber, other) VALUES (26, 29, 6000, 'Szeged', 'Gogol', 10, 'a');
INSERT INTO public.locations (id, u_id, postcode, city, street, streetnumber, other) VALUES (19, 10, 6725, 'Szeged', 'Fa', 30, 'B');
INSERT INTO public.locations (id, u_id, postcode, city, street, streetnumber, other) VALUES (33, 38, 6724, 'Szeged', 'Mars tér', 16, '');
INSERT INTO public.locations (id, u_id, postcode, city, street, streetnumber, other) VALUES (34, 39, 6724, 'Szeged', 'Szeged Plaza', 1, '');
INSERT INTO public.locations (id, u_id, postcode, city, street, streetnumber, other) VALUES (36, 41, 6722, 'Szeged', 'Jókai u.', 1, '');
INSERT INTO public.locations (id, u_id, postcode, city, street, streetnumber, other) VALUES (32, 37, 6720, 'Szeged', 'Kárász', 11, '');
INSERT INTO public.locations (id, u_id, postcode, city, street, streetnumber, other) VALUES (37, 42, 6720, 'Szeged', 'Kárász', 17, '');
INSERT INTO public.locations (id, u_id, postcode, city, street, streetnumber, other) VALUES (30, 35, 6720, 'Szeged', 'Jókai', 1, '');
INSERT INTO public.locations (id, u_id, postcode, city, street, streetnumber, other) VALUES (21, 24, 6726, 'Szeged', 'Rigó', 1, '');
INSERT INTO public.locations (id, u_id, postcode, city, street, streetnumber, other) VALUES (38, 43, 6726, 'Szeged', 'Fő fasor', 16, '');
INSERT INTO public.locations (id, u_id, postcode, city, street, streetnumber, other) VALUES (20, 23, 1000, 'Szeged', 'József', 10, '21');
INSERT INTO public.locations (id, u_id, postcode, city, street, streetnumber, other) VALUES (35, 40, 6720, 'Szeged', 'Kölcsey', 4, '');
INSERT INTO public.locations (id, u_id, postcode, city, street, streetnumber, other) VALUES (39, 44, 6724, 'Szeged', 'Londoni krt.', 3, '');
INSERT INTO public.locations (id, u_id, postcode, city, street, streetnumber, other) VALUES (31, 36, 6720, 'Szeged', 'Kárász', 2, '');
INSERT INTO public.locations (id, u_id, postcode, city, street, streetnumber, other) VALUES (40, 45, 1234, 'Yemen', 'Ez utca', 89, '');
INSERT INTO public.locations (id, u_id, postcode, city, street, streetnumber, other) VALUES (41, 46, 6720, 'Szeged', 'Kárász', 6, '');
INSERT INTO public.locations (id, u_id, postcode, city, street, streetnumber, other) VALUES (45, 50, 6700, 'Szeged', 'tesz', 3, '');
INSERT INTO public.locations (id, u_id, postcode, city, street, streetnumber, other) VALUES (46, 51, 6700, 'Szeged', 'Futárok tere', 48, '');